### ISSUE TITLE
segmentation任务缺少模型定义

### ISSUE THREAD

**Issue by kongdebug** [lwCVer/DecoupleNet#2]
非常感谢你开源了代码！在学习的过程中我发现缺失了UNetFormer_DecoupleNet_D2这个类的定义，不知道这在哪里能获取呢？

**Comment by lwCVer** [comment]
感谢您的反馈，我们更新了配置文件。

**Comment by lwCVer** [comment]
> 非常感谢你开源了代码！在学习的过程中我发现缺失了UNetFormer_DecoupleNet_D2这个类的定义，不知道这在哪里能获取呢？

感谢您的反馈，我们更新了配置文件。

**Comment by kongdebug** [comment]
> > 非常感谢你开源了代码！在学习的过程中我发现缺失了UNetFormer_DecoupleNet_D2这个类的定义，不知道这在哪里能获取呢？
> 
> 感谢您的反馈，我们更新了配置文件。

谢谢，可以跑起来了，指标也算正常
